<?php

namespace NTI\AutoDeleteBundle\Repository;

/**
 * AutoDeleteEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoDeleteEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
